apiVersion: v1
kind: ReplicationController
metadata:
  name: eureka-server
  labels:
    k8s-app: eureka-server
    version: v0
spec:
  replicas: 1
  selector:
    k8s-app: eureka-server
    version: v0
  template:
    metadata:
      labels:
        k8s-app: eureka-server
        version: v0
    spec:
      containers:
      - name: eureka-server
        image: localhost:5000/eureka-server
        env:
        ports:
        - containerPort: 8761
          name: eureka-server
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    k8s-app: eureka-server
spec:
  selector:
    k8s-app: eureka-server
  ports:
  - name: eureka-server
    port: 8761
    protocol: TCP
  type: NodePort
