spring:
  application:
    name: SimpleMicroservice
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
logging:
  level:
    org.springframework: DEBUG
    reactor: DEBUG

