spring:
  application:
    name: SpringKubeGateway
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
server:
  port: 80
logging:
  level:
    org.springframework: DEBUG
    reactor: DEBUG
