apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway-v0
  labels:
    k8s-app: gateway
    version: v0
spec:
  replicas: 1
  selector:
    k8s-app: gateway
    version: v0
  template:
    metadata:
      labels:
        k8s-app: gateway
        version: v0
    spec:
      containers:
      - name: gateway
        image: localhost:5000/gateway
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://$${EUREKA_SERVER_SERVICE_HOST}:$${EUREKA_SERVER_SERVICE_PORT}/eureka/"
        - name: SERVER_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: microservice
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    k8s-app: gateway
spec:
  selector:
    k8s-app: gateway
  ports:
  - name: microservice
    port: 8080
    protocol: TCP
  type: NodePort
